---
version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.1
    hostname: kibana
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

 