version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: "zookeeper"
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: "kafka"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge